import React, { useState, useContext, useEffect } from 'react';
import { StudentContext } from '../../context/StudentContext';
import DashboardHeader from '../../components/layout/DashboardHeader';
import DashboardFooter from '../../components/layout/DashboardFooter';
import Sidebar from '../../components/layout/Sidebar';
import api from '../../lib/api';

export default function AutoGeneratedLeavesPage() {
    const { user } = useContext(StudentContext);
    const [isSidebarOpen, setIsSidebarOpen] = useState(true);
    const [autoGeneratedLeaves, setAutoGeneratedLeaves] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        const fetchAutoGeneratedLeaves = async () => {
            try {
                const token = localStorage.getItem('token');
                if (!token) return;
                
                const response = await api.get('/api/auth/student/auto-generated-leaves', {
                    headers: { Authorization: `Bearer ${token}` },
                });
                setAutoGeneratedLeaves(response.data.leaves || []);
            } catch (error) {
                console.error('Failed to fetch auto-generated leaves:', error.response?.data?.error || error.message);
                setError('Failed to fetch auto-generated leaves');
            } finally {
                setIsLoading(false);
            }
        };

        fetchAutoGeneratedLeaves();
    }, []);

    const getStatusClass = (status) => {
        const lowerStatus = (status || '').toLowerCase();
        if (lowerStatus.includes('approved')) return 'bg-green-100 text-green-800';
        if (lowerStatus.includes('pending')) return 'bg-yellow-100 text-yellow-800';
        if (lowerStatus.includes('rejected')) return 'bg-red-100 text-red-800';
        return 'bg-gray-100 text-gray-800';
    };

    const getLeaveTypeClass = (leaveType) => {
        switch (leaveType) {
            case 'CL': return 'bg-cyan-100 text-cyan-800';
            case 'DL': return 'bg-green-100 text-green-800';
            case 'LWP': return 'bg-red-100 text-red-800';
            default: return 'bg-gray-100 text-gray-800';
        }
    };

    return (
        <div className="w-screen h-screen bg-white flex flex-col">
            <DashboardHeader />
            <div className="flex flex-1 overflow-y-auto relative">
                <Sidebar
                    isSidebarOpen={isSidebarOpen}
                    onSidebarToggle={() => setIsSidebarOpen(!isSidebarOpen)}
                    activeItem="Auto Generated Leaves"
                />
                <main className="flex-1 p-4 md:p-6 overflow-y-auto bg-gray-50">
                    <div className="flex justify-between items-center mb-6">
                        <div>
                            <h2 className="text-2xl font-bold text-gray-500 tracking-tight">Auto Generated Leaves</h2>
                            <p className="text-gray-600 mt-1">Leaves automatically generated from Excel attendance uploads</p>
                        </div>
                    </div>

                    {isLoading ? (
                        <div className="flex items-center justify-center py-12">
                            <div className="text-center">
                                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-cyan-600 mx-auto"></div>
                                <p className="text-gray-600 mt-4">Loading auto-generated leaves...</p>
                            </div>
                        </div>
                    ) : error ? (
                        <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
                            <p className="text-red-600">{error}</p>
                        </div>
                    ) : autoGeneratedLeaves.length === 0 ? (
                        <div className="bg-gray-50 border border-gray-200 rounded-lg p-8 text-center">
                            <div className="text-gray-400 mb-4">
                                <svg className="w-16 h-16 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                                </svg>
                            </div>
                            <h3 className="text-lg font-semibold text-gray-700 mb-2">No Auto-Generated Leaves</h3>
                            <p className="text-gray-600">No auto-generated leaves found. These are created when Excel attendance files are uploaded.</p>
                        </div>
                    ) : (
                        <div className="space-y-4">
                            {autoGeneratedLeaves.map((leave, index) => (
                                <div key={leave.id || index} className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                                    <div className="flex items-start justify-between">
                                        <div className="flex-1">
                                            <div className="flex items-center gap-3 mb-3">
                                                <span className={`px-3 py-1 rounded-full text-sm font-semibold ${getLeaveTypeClass(leave.leaveType)}`}>
                                                    {leave.leaveType}
                                                </span>
                                                <span className={`px-3 py-1 rounded-full text-sm font-semibold ${getStatusClass(leave.status)}`}>
                                                    {leave.status}
                                                </span>
                                            </div>
                                            
                                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                                                <div>
                                                    <p className="text-sm text-gray-500 mb-1">Start Date</p>
                                                    <p className="font-semibold text-gray-900">{leave.startDate}</p>
                                                </div>
                                                <div>
                                                    <p className="text-sm text-gray-500 mb-1">End Date</p>
                                                    <p className="font-semibold text-gray-900">{leave.endDate}</p>
                                                </div>
                                                <div>
                                                    <p className="text-sm text-gray-500 mb-1">Application Date</p>
                                                    <p className="font-semibold text-gray-900">{leave.applicationDate}</p>
                                                </div>
                                            </div>
                                            
                                            {leave.remark && (
                                                <div className="bg-gray-50 rounded-lg p-4">
                                                    <p className="text-sm text-gray-500 mb-1">Remark</p>
                                                    <p className="text-gray-700">{leave.remark}</p>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </main>
            </div>
            <DashboardFooter />
        </div>
    );
}
