import React, { useState, useContext, useEffect } from 'react';
import axiosInstance from '../../utils/axiosInstance';
import { API_ENDPOINTS } from '../../config/api';
import { StudentContext } from '../../context/StudentContext';
import DashboardHeader from '../../components/layout/DashboardHeader';
import DashboardFooter from '../../components/layout/DashboardFooter';
import Sidebar from '../../components/layout/Sidebar';

export default function AutoGeneratedLeavesPage() {
    const { user } = useContext(StudentContext);
    const [isSidebarOpen, setIsSidebarOpen] = useState(true);
    const [autoGeneratedLeaves, setAutoGeneratedLeaves] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        const fetchAutoGeneratedLeaves = async () => {
            try {
                const token = localStorage.getItem('token');
                if (!token) {
                    setError('No authentication token found');
                    setIsLoading(false);
                    return;
                }

                const response = await axiosInstance.get(API_ENDPOINTS.STUDENT_AUTO_LEAVES, {
                    headers: { Authorization: `Bearer ${token}` },
                });

                if (response.data && response.data.leaves) {
                    setAutoGeneratedLeaves(response.data.leaves);
                } else {
                    setAutoGeneratedLeaves([]);
                }
            } catch (err) {
                console.error('Error fetching auto-generated leaves:', err);
                setError(err.response?.data?.error || 'Failed to fetch auto-generated leaves');
            } finally {
                setIsLoading(false);
            }
        };

        fetchAutoGeneratedLeaves();
    }, []);

    return (
        <div className="min-h-screen bg-gray-50">
            <DashboardHeader 
                user={user} 
                onMenuClick={() => setIsSidebarOpen(!isSidebarOpen)} 
            />
            <div className="flex">
                <Sidebar isOpen={isSidebarOpen} />
                <div className={`flex-1 transition-all duration-300 ${isSidebarOpen ? 'ml-64' : 'ml-0'}`}>
                    <main className="p-6">
                        <div className="max-w-7xl mx-auto">
                            <h1 className="text-3xl font-bold text-gray-900 mb-6">
                                Auto-Generated Leaves
                            </h1>

                            {isLoading ? (
                                <div className="flex justify-center items-center h-64">
                                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
                                </div>
                            ) : error ? (
                                <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
                                    {error}
                                </div>
                            ) : autoGeneratedLeaves.length === 0 ? (
                                <div className="bg-white rounded-lg shadow p-6 text-center">
                                    <p className="text-gray-500">No auto-generated leaves found.</p>
                                </div>
                            ) : (
                                <div className="bg-white rounded-lg shadow overflow-hidden">
                                    <table className="min-w-full divide-y divide-gray-200">
                                        <thead className="bg-gray-50">
                                            <tr>
                                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    Date
                                                </th>
                                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    Type
                                                </th>
                                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    Reason
                                                </th>
                                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    Status
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody className="bg-white divide-y divide-gray-200">
                                            {autoGeneratedLeaves.map((leave, index) => (
                                                <tr key={index} className="hover:bg-gray-50">
                                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                        {new Date(leave.date).toLocaleDateString()}
                                                    </td>
                                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                        {leave.type || 'N/A'}
                                                    </td>
                                                    <td className="px-6 py-4 text-sm text-gray-900">
                                                        {leave.reason || 'Auto-generated leave'}
                                                    </td>
                                                    <td className="px-6 py-4 whitespace-nowrap">
                                                        <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                                                            leave.status === 'APPROVED' 
                                                                ? 'bg-green-100 text-green-800' 
                                                                : leave.status === 'PENDING'
                                                                ? 'bg-yellow-100 text-yellow-800'
                                                                : 'bg-gray-100 text-gray-800'
                                                        }`}>
                                                            {leave.status || 'PENDING'}
                                                        </span>
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            )}
                        </div>
                    </main>
                    <DashboardFooter />
                </div>
            </div>
        </div>
    );
}
