import { Routes, Route, Navigate } from 'react-router-dom';

// Context Providers
import AuthContextProvider from './context/AuthContextProvider';
import StudentContextProvider from './context/StudentContextProvider';
import GuideContextProvider from './context/GuideContextProvider';
import { DeanContextProvider } from './context/DeanContext.jsx';

// Page Components
import Login from './pages/Login.jsx';
import SignUp from './pages/SignUp.jsx';
import ForgotPassword from './pages/ForgotPassword.jsx';
import StudentProfileForm from './pages/student/StudentForm.jsx';
import StudentDashboard from './pages/student/StudentDashboard.jsx';
import StudentProfilePage from './pages/student/StudentProfilePage.jsx';
import PendingApprovalPage from './pages/student/PendingApprovalPage.jsx';
import ApplyLeavePage from './pages/student/ApplyLeavePage.jsx';
import EnjoyedLeavePage from './pages/student/EnjoyedLeavePage.jsx';
import AutoGeneratedLeavesPage from './pages/student/AutoGeneratedLeavesPage.jsx';
import GuideDashboard from './pages/guide/GuideDashboard.jsx';
import DevelopersPage from './pages/DevelopersPage.jsx';
import BatchInfoPage from './pages/guide/BatchInfoPage.jsx';
import GuideReportGenerationPage from './pages/guide/GuideReportGenerationPage.jsx';
import GuideLayout from './components/layout/GuideLayout.jsx';
import OperatorDashboard from './pages/operator/OperatorDashboard.jsx';
import OperatorImportExcelPage from './pages/operator/ImportExcelPage.jsx';
import PendingStudentsPage from './pages/operator/PendingStudentsPage.jsx';
import StudentManagementPage from './pages/operator/StudentManagementPage.jsx';
import GuideManagementPage from './pages/operator/GuideManagementPage.jsx';
import ReportGenerationPage from './pages/operator/ReportGenerationPage.jsx';
import OperatorLayout from './components/layout/OperatorLayout.jsx';
import DeanDashboard from './pages/dean/DeanDashboard.jsx';
import DeanLeaveCalendar from './pages/dean/DeanLeaveCalendar.jsx';
import DeanReportGenerationPage from './pages/dean/DeanReportGenerationPage.jsx';
import StudentDetailPage from './pages/dean/StudentDetailPage.jsx';

// Utility Component for protecting routes
import ProtectedRoute from './components/auth/ProtectedRoute.jsx';

function App() {
  return (
    <AuthContextProvider>
      <Routes>
        {/* Public Routes */}
        <Route path="/" element={<Login />} />
        <Route path="/signup" element={<SignUp />} />
        <Route path="/forgot-password" element={<ForgotPassword />} />
        <Route path="/developers" element={<DevelopersPage />} />

        {/* Student Routes */}
        <Route path="/student/StudentForm" element={<StudentProfileForm />} />
        <Route path="/student/pending-approval" element={<PendingApprovalPage />} />
        <Route path="/student/apply-leave" element={<ApplyLeavePage />} />
        <Route path="/student/enjoyed-leave" element={<EnjoyedLeavePage />} />
        <Route 
          path="/student/auto-generated-leaves" 
          element={
            <StudentContextProvider>
              <AutoGeneratedLeavesPage />
            </StudentContextProvider>
          } 
        />
        <Route 
          path="/student/dashboard" 
          element={
            <StudentContextProvider>
              <StudentDashboard />
            </StudentContextProvider>
          } 
        />
        <Route
          path="/student/profile"
          element={
            <StudentContextProvider>
              <StudentProfilePage />
            </StudentContextProvider>
          }
        />

        {/* --- GUIDE ROUTES --- */}
        {/* This structure is correct. It uses GuideLayout as a wrapper for guide pages. */}
        <Route path="/guide" element={
          <GuideContextProvider>
            <GuideLayout />
          </GuideContextProvider>
        }>
          <Route index element={<Navigate to="dashboard" replace />} />
          <Route path="dashboard" element={<GuideDashboard />} />
          <Route path="batch-info" element={<BatchInfoPage />} />
          <Route path="report-generation" element={<GuideReportGenerationPage />} />
        </Route>

        {/* --- OPERATOR ROUTES --- */}
        <Route path="/operator" element={
          <OperatorLayout />
        }>
          <Route index element={<Navigate to="dashboard" replace />} />
          <Route path="dashboard" element={<OperatorDashboard />} />
          <Route path="import-excel" element={<OperatorImportExcelPage />} />
          <Route path="pending-students" element={<PendingStudentsPage />} />
          <Route path="student-management" element={<StudentManagementPage />} />
          <Route path="guide-management" element={<GuideManagementPage />} />
          <Route path="report-generation" element={<ReportGenerationPage />} />
        </Route>

        {/* --- DEAN ROUTES --- */}
        <Route 
          path="/dean/dashboard" 
          element={
            <DeanContextProvider>
              <DeanDashboard />
            </DeanContextProvider>
          } 
        />
        <Route 
          path="/dean/calendar" 
          element={
            <DeanContextProvider>
              <DeanLeaveCalendar />
            </DeanContextProvider>
          } 
        />
        <Route 
          path="/dean/report-generation" 
          element={
            <DeanContextProvider>
              <DeanReportGenerationPage />
            </DeanContextProvider>
          } 
        />
        <Route 
          path="/dean/student/:id" 
          element={
            <DeanContextProvider>
              <StudentDetailPage />
            </DeanContextProvider>
          } 
        />

        {/* Protected Routes */}
        <Route element={<ProtectedRoute />}>
          {/* Add any routes that require authentication here */}
        </Route>
      </Routes>
    </AuthContextProvider>
  );
}

export default App;
